#
# Makefile -- build test client for the guiderport interface
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
gpclient:	gpclient.c
	gcc -std=gnu99 -Wall -O -g -o gpclient gpclient.c -lusb-1.0
